# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy your application files to the container
COPY . ./

# Expose the port your application will run on
EXPOSE 8080

# Define the command to start your Node.js application
CMD ["node", "dist/app.js"]
